app_stock_exchange:
    path: /exchange
    controller: App\Controller\TransactionController::createTransaction

extension:
    path: /exchange/userTransactions/{id}
    defaults:
        _controller: App\Controller\TransactionController::EditTransaction
        id: 1
